name: project-setup
description: setup project, jdk, and gradle cache

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
       distribution: 'zulu'
       java-version: 11
       cache: gradle

    - name: Cache Gradle and wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}